const names={video:'视频作品',visual:'视觉作品',writing:'文案作品',artist:'宣传策划项目'};
const grid=document.querySelector('#work-grid'),detail=document.querySelector('#detail'),lightbox=document.querySelector('#lightbox');
function el(tag,className,text){const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n}
function originalLink(p,className='original-link'){
 const href=p.link&&safeURL(p.link);if(!href)return null;
 const a=el('a',className,(p.type==='微博账号'?'访问账号主页':p.category==='visual'?'查看原帖':p.category?'观看原帖':'访问账号主页')+(p.platform?' · '+p.platform:''));a.href=href;a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-label','在新标签页观看'+p.title+'原帖');return a;
}
let workExpanded=false,workFilter='all';
function render(filter='all'){
 workFilter=filter;grid.replaceChildren();const items=portfolioContent.projects.filter(p=>filter==='all'||p.category===filter);const shown=workExpanded?items:items.slice(0,6);shown.forEach(p=>{
 const card=el('article','work-card '+p.category+(p.kind==='showcase'?' showcase-card':'')),visual=el('button','card-visual');visual.type='button';visual.setAttribute('aria-label','查看'+p.title+'详情');
 if(p.image){const im=el('img');im.src=p.image;im.alt=p.title+'封面';im.loading='lazy';if(p.aspect)im.width=p.width||800;if(p.aspect)im.height=p.height||Math.round(800/p.aspect);visual.append(im)}else{visual.append(el('span','placeholder-code',p.category==='video'?'PLAY / EDIT':'WRITE / CREATE'),el('strong','placeholder-title',p.category==='video'?'影像':'文字'),el('span','placeholder-label',p.category==='video'?'视频封面待更新':'文案截图待更新'))}
 if(p.category==='video')visual.append(el('span','preview-play','播放视频'));if(p.status)visual.append(el('span','status',p.status));visual.addEventListener('click',()=>openDetail(p));
 const info=el('div','card-info');info.append(el('span','card-type',p.type),el('h3','',p.title));
 const actions=el('div','card-actions'),details=el('button','card-open','查看详情');details.type='button';details.addEventListener('click',()=>openDetail(p));actions.append(details);
 if(p.category==='video'){const a=originalLink(p);if(a)actions.append(a)}
 info.append(actions);card.append(visual,info);grid.append(card)
 });const toggle=document.querySelector('#work-expand');toggle.hidden=items.length<=6;toggle.textContent=workExpanded?'收起作品':'查看全部作品（'+items.length+'）';toggle.setAttribute('aria-expanded',String(workExpanded));
}
document.querySelector('#work-expand').addEventListener('click',()=>{workExpanded=!workExpanded;render(workFilter);if(!workExpanded)document.querySelector('#work').scrollIntoView({block:'start'})});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));workExpanded=false;render(b.dataset.filter)}));
function safeURL(value){try{const u=new URL(value,location.href);return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}}
function openDetail(p,parent=null){
 document.querySelector('#case-back')?.remove();document.querySelector('#detail-metrics')?.remove();
 if(parent){const back=el('button','',parent.artist?'返回艺人项目':'返回账号档案');back.id='case-back';back.type='button';back.addEventListener('click',()=>openDetail(parent));document.querySelector('.dialog-bar').prepend(back)}
document.querySelector('#detail-category').textContent=names[p.category]||'社媒运营';document.querySelector('#detail-title').textContent=p.title;document.querySelector('#detail-description').textContent=p.description;const media=document.querySelector('#detail-media');media.classList.toggle('series-thumbnails',p.thumbnailGallery===true||p.id==='emma-color-series'||p.id==='harry-potter-color-series');media.replaceChildren();if(p.video&&safeURL(p.video)){const v=el('video');if(p.image)v.poster=p.image;v.src=safeURL(p.video);v.controls=true;v.preload='metadata';v.playsInline=true;media.append(v)}if(p.document&&safeURL(p.document)){const a=el('a','external-link','查看完整策划案（PDF）');a.href=safeURL(p.document);a.target='_blank';a.rel='noopener noreferrer';media.append(a)}if(p.link&&safeURL(p.link)){const a=originalLink(p,'external-link');if(a)media.append(a)}(p.images||[]).forEach(src=>{const b=el('button','gallery-image');b.type='button';b.setAttribute('aria-label','放大查看'+p.title);const im=el('img');im.src=src;im.alt=p.title;im.loading='lazy';b.append(im);b.addEventListener('click',()=>{const zoom=document.querySelector('#lightbox-image');zoom.src=src;zoom.alt=p.title;lightbox.showModal()});media.append(b)});const sections=document.querySelector('#detail-sections');sections.replaceChildren();if(!['performance','showcase'].includes(p.kind)&&(p.category==='video'||p.category==='visual'||p.category==='artist')){const copy=el('section','case-section');copy.append(el('h3','','作品文案'),el('p','',p.caption||'文案与原帖截图待更新。'));(p.captionImages||[]).forEach(src=>{const b=el('button','gallery-image');b.type='button';b.setAttribute('aria-label','放大查看文案截图');const im=el('img');im.src=src;im.alt='作品文案截图';b.append(im);b.addEventListener('click',()=>{document.querySelector('#lightbox-image').src=src;document.querySelector('#lightbox-image').alt='作品文案截图';lightbox.showModal()});copy.append(b)});sections.append(copy)}if(p.metrics?.length){const metrics=el('dl','case-metrics');metrics.id='detail-metrics';p.metrics.forEach(([label,value])=>{const pair=el('div');pair.append(el('dt','',label),el('dd','',value));metrics.append(pair)});document.querySelector('#detail-description').after(metrics)}
 if(p.cases?.length){const batches=p.platform==='抖音'?[{title:'影视账号 · 代表作品',items:p.cases.filter(c=>c.type!=='匿名数据案例')},{title:'私人账号 · 匿名数据成果',description:'单篇最高 853.2 万播放 · 146.8 万点赞，3 篇作品播放破百万。',items:p.cases.filter(c=>c.type==='匿名数据案例')}]:[{title:p.platform==='微博'?'账号与内容案例':p.category==='artist'?'代表宣传内容':'代表视频与运营数据',items:p.cases}];batches.filter(b=>b.items.length).forEach(batch=>{const group=el('section','case-section');group.append(el('h3','',batch.title));if(batch.description)group.append(el('p','data-highlight',batch.description));const list=el('div','performance-cases');batch.items.forEach(item=>{const card=el('article','performance-card'+(item.type==='匿名数据案例'?' anonymous-data-card':''));const cover=el('button','performance-cover');cover.type='button';cover.setAttribute('aria-label','查看'+item.title);const image=el('img');image.src=item.image;image.alt=item.title+'作品截图';image.loading='lazy';cover.append(image);cover.addEventListener('click',()=>openDetail(item,p));const info=el('div','performance-info');info.append(el('h4','',item.title),el('p','',(item.metrics||[]).slice(0,2).map(([label,value])=>label+' '+value).join(' · ')));const actions=el('div','card-actions');const details=el('button','','查看数据与复盘');details.textContent=item.type==='微博账号'?'查看账号档案':item.category==='visual'?'查看图文与复盘':'查看数据与复盘';details.type='button';details.addEventListener('click',()=>openDetail(item,p));actions.append(details);const link=originalLink(item);if(link)actions.append(link);info.append(actions);card.append(cover,info);list.append(card)});group.append(list);sections.append(group)})}
 (p.sections||[]).forEach(([title,text])=>{const s=el('section','case-section'+(title==='数据说明'?' data-note':''));s.append(el('h3','',title),el('p','',text));sections.append(s)});if(!detail.open)detail.showModal();detail.scrollTop=0}
portfolioContent.accounts.forEach(account=>{const b=el('button','account-card');b.type='button';b.append(el('span','account-platform',account.platform),el('strong','',account.title),el('span','account-action','查看运营档案'));b.addEventListener('click',()=>openDetail(account));document.querySelector('#platform-accounts').append(b)});
const artistRoot=document.querySelector('#artist-groups'),artists=['杨幂','宋茜','王天辰','杨洋',...new Set(portfolioContent.artistProjects.map(p=>p.artist).filter(a=>!['杨幂','宋茜','王天辰','杨洋'].includes(a)))];
if(!artists.length){const empty=el('div','artist-empty');empty.append(el('h3','','宣传项目待更新'),el('p','','按项目主题整理视频、文案、策划方案与传播成果。'));artistRoot.append(empty)}
artists.forEach(artist=>{const group=el('section','artist-group');group.append(el('h3','',artist));portfolioContent.artistProjects.filter(p=>p.artist===artist).forEach(project=>{const b=el('button','artist-project');b.type='button';b.append(el('strong','',project.title),el('span','',project.type||'视频 · 文案 · 策划'));b.addEventListener('click',()=>openDetail({...project,category:'artist'}));group.append(b)});artistRoot.append(group)});
function closeDialog(d){d.querySelectorAll('video').forEach(v=>v.pause());d.close()}
document.querySelector('#close-detail').addEventListener('click',()=>closeDialog(detail));document.querySelector('#close-lightbox').addEventListener('click',()=>closeDialog(lightbox));[detail,lightbox].forEach(d=>{d.addEventListener('close',()=>d.querySelectorAll('video').forEach(v=>v.pause()));d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog(d)}})});document.querySelector('#year').textContent=new Date().getFullYear();render();

const profile=portfolioContent.profile;document.querySelectorAll('[data-profile]').forEach(n=>n.textContent=profile[n.dataset.profile]||'');document.title=profile.name+' · 个人作品集';if(profile.heroImage)document.querySelector('.hero-art img').src=profile.heroImage;else document.querySelector('.hero-art').hidden=true;document.querySelector('.hero-art>span').textContent='创作作品';document.querySelector('.draft-note').hidden=true;
